### ISSUE TITLE
Could we have a revamp of the current website and logo?

### ISSUE THREAD

**Issue by geoyws** [wekan/wekan.github.io#14]
Folks might have a harder time pitching to management because of how things look. Just my 2 cents. Appreciate the hard work!

**Comment by xet7** [comment]
@geoyws 

Depends if you have some improvement suggestions.

**Comment by xet7** [comment]
In general, I'm a coder. I'm still waiting for feedback to Wekan UI from 2 designers.

[Wekan website code is here](https://github.com/wekan/wekan.github.io). Please keep location of files the same, because those are embedded in Wekan GitHub wiki. You can add changes to index.html etc as pull request.

For Wekan docs, there are these websites, started by some at Wekan community:
- https://github.com/wekan/wekanhow
- https://github.com/wekan/wekan-doc

I would very gladly like to see Wekan community to improve website and docs. I am already using a lot of my free time to maintain Wekan. Only small part of features and fixes is funded, and coding takes a lot of time.

**Comment by xet7** [comment]
In general, please add pull requests directly to those repos. Thanks!

**Comment by xet7** [comment]
Hmm, actually I don't understand why?
- Website shows screenshots and most important links. I did organize it now so that download is separate section. Many do like the current Wekan website.
- Wekan logo has been designed by professional designers, and has been updated to remove shadow.

**Comment by xet7** [comment]
Anyway, I'm waiting for any design suggestions as comments or pull requests.
